//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CUSTOMERS()
        {
            this.TBL_DIRECTIONS = new HashSet<TBL_DIRECTIONS>();
            this.TBL_CONTACTMETHODS = new HashSet<TBL_CONTACTMETHODS>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string SEX { get; set; }
        public string STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DIRECTIONS> TBL_DIRECTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONTACTMETHODS> TBL_CONTACTMETHODS { get; set; }
    }
}
